services:
  - type: web
    name: books-backend
    env: node
    plan: free
    buildCommand: npm install --production=false
    startCommand: NODE_OPTIONS='--max-old-space-size=400' npm run start:api
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: NODE_OPTIONS
        value: --max-old-space-size=400
      - key: DATABASE_URL
        fromDatabase:
          name: books_db # Agar Render-da DB bo'lsa, aks holda qo'lda kiriting
      - key: BOT_TOKEN
        sync: false # Render dashboard'dan qo'lda qo'shing
