services:
  - type: web
    name: books-backend
    env: node
    plan: free
    buildCommand: npm install typescript --save-dev && npm run build:server && cd server && npm install --omit=dev --no-audit --no-fund
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: NODE_OPTIONS
        value: --max-old-space-size=400
      - key: DATABASE_URL
        fromDatabase:
          name: books_db # Agar Render-da DB bo'lsa, aks holda qo'lda kiriting
      - key: BOT_TOKEN
        sync: false # Render dashboard'dan qo'lda qo'shing
