services:
  - type: web
    name: books-backend
    runtime: node
    plan: standard
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: NODE_OPTIONS
        value: --max-old-space-size=1500 --expose-gc --no-warnings
      - key: DATABASE_URL
        fromDatabase:
          name: books_db # Agar Render-da DB bo'lsa, aks holda qo'lda kiriting
      - key: BOT_TOKEN
        sync: false # Render dashboard'dan qo'lda qo'shing
      - key: ESKIZ_EMAIL
        sync: false
      - key: ESKIZ_PASSWORD
        sync: false
      - key: ESKIZ_FROM
        sync: false
      - key: ESKIZ_CALLBACK_URL
        sync: false
      - key: OTP_HASH_SALT
        sync: false
